# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Qi Chen Space
logo: "/assets/img/IMG_2789.PNG"
email: qi.chen.2019uk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Feel free to reach out to me through the contact information provided on this website. Let's explore how we can work together to create something amazing!

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  kiqi7
medium_username: kiqi7

# Build settings
theme: minima
plugins:
  - jekyll-feed

footer:
  copyright: "Copyright © 2024 Your Name. All rights reserved."
  message: "Thank you for visiting my website!"

collections:
  pages:
    output: true
    permalink: /blog/:categories/:title/


defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Qi
      categories: [machine-learning]
      tags: [deep-learning, neural-networks]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
